Search feature
ESGI-Symfony/Symfony_UX pull request #36
Opened 2023-02-12 12:23 UTC by Quozul

2023-02-13 10:05 UTC, Nicolas-Wadoux-ESGI requested changes

2023-02-13 10:10 UTC, Quozul commented on src/Controller/Front/RentalController.php
> +    public function access(Request $request, Rental $rental): Response
Je croyais que c'était un projet de Symfony, pas de JS

2023-02-13 17:16 UTC, Quozul commented on src/Controller/Front/RentalController.php
> +    #[Route('/book', name: '_book')]
C'est la route pour quand tu veux réserver, quand on clique sur le bouton "Book now"

2023-02-13 17:18 UTC, Quozul commented on templates/components/details-card.html.twig
> +        <div class="icons">
moi

2023-02-13 17:18 UTC, Quozul commented on src/Controller/Front/SearchController.php
> +        $results = $query
Pas vraiment utile de mettre le même retour sur toutes les lignes

2023-02-13 17:18 UTC, Quozul commented on src/Controller/Front/SearchController.php
> +<?php
On peut chercher depuis la home déjà

2023-02-13 17:21 UTC, Quozul commented on templates/front/search/index.html.twig
> +                    <button class="btn btn-primary" name="page" value="{{ previous_page }}">{{ "search.previous" | trans }}</button>
Je connaissais pas, merci

2023-02-18 10:34 UTC, Quozul commented on templates/front/rental/base.html.twig
> +                    </div>
et il fait quoi ce bouton ?

2023-02-19 11:40 UTC, Nicolas-Wadoux-ESGI commented on templates/front/rental/access.html.twig
> +            {% for transport in transports %}
Autre PR

2023-02-19 11:40 UTC, Nicolas-Wadoux-ESGI approved these changes

2023-02-19 11:51 UTC, merged