Feature/reset password
ESGI-Symfony/Symfony_UX pull request #43
Opened 2023-02-20 20:42 UTC by Xaless2

2023-02-21 20:27 UTC, Nicolas-Wadoux-ESGI requested changes

2023-02-21 20:27 UTC, Nicolas-Wadoux-ESGI commented on templates/partials/_input_password.html.twig
> +<script>
C'est pas possible de mettre dans script dans les twig (règles serveur), tu peux deplacer ca dans un fichier .js ?
Et ducoup utilise que des id et pas des class (pour .password-toggle et .password-toggle-off), sauf si tu veux generaliser le script

2023-02-21 20:27 UTC, Nicolas-Wadoux-ESGI commented on templates/reset_password/email.html.twig
> +<body style="font-family: Arial, sans-serif;background: linear-gradient(167.95deg, #000000 0%, #02043C 58.4%, #390F40 86.52%, #450050 100%);display: flex;justify-content: center;align-items: center;
tu peux mettre des balise style plutot ? (la par contre pas le choix de le mettre dans le twig, mais ca devrait pas poser problème)

2023-02-21 20:27 UTC, Nicolas-Wadoux-ESGI commented on templates/security/login.html.twig
> +        <script>
pareil ici pour le js (le meme script ducoup devrait marcher, même sans selectorAll)

2023-02-21 20:27 UTC, Nicolas-Wadoux-ESGI commented on templates/reset_password/request.html.twig
> +            <button class="btn btn-primary">{{ bootstrap_icon("rocket-takeoff") }} Sent email</button>
Tu as mis aucune clé de traduction
Par exemple ici tu dois faire {{ send_recovery_email | trans }}
et dans translations/templates/messages.en.yml mettre send_recovery_email: Send recovery email
Tu peux faire ca partout stp ? (tous les templates même ceux des mails)

2023-02-21 20:27 UTC, Nicolas-Wadoux-ESGI commented on templates/registration/register.html.twig
> +        {{ include('partials/_input_password.html.twig', {input: registrationForm.plainPassword}) }}
Les inputs sont pas dans le même style, possible de corriger ?
<img width="437" alt="image" src="https://user-images.githubusercontent.com/114507587/220450994-cfbc52f4-eeea-41e4-93e8-c24dd76d33fb.png">

2023-02-25 17:14 UTC, Quozul approved these changes
cbo

2023-02-25 17:25 UTC, Nicolas-Wadoux-ESGI approved these changes

2023-02-25 17:25 UTC, merged